name: robodiff
channels:
  - pytorch3d
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20211102.0
  - absl-py=2.1.0
  - accelerate=0.13.2
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.3.1
  - alsa-lib=1.2.8
  - antlr-python-runtime=4.9.3
  - aom=3.5.0
  - arrow-cpp=8.0.0
  - asciitree=0.3.3
  - asttokens=2.4.1
  - async-timeout=4.0.3
  - attr=2.5.1
  - attrs=24.2.0
  - av=10.0.0
  - aws-c-common=0.6.8
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.185
  - blas=1.0
  - blinker=1.8.2
  - blosc=1.21.5
  - boost-cpp=1.81.0
  - boto3=1.24.96
  - botocore=1.27.96
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.33.1
  - c-blosc2=2.12.0
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.0
  - cairo=1.16.0
  - certifi=2024.8.30
  - cffi=1.15.1
  - cfitsio=4.1.0
  - charls=2.3.4
  - charset-normalizer=3.3.2
  - click=8.0.4
  - cloudpickle=3.0.0
  - cmake=3.24.3
  - colorama=0.4.6
  - contourpy=1.3.0
  - cryptography=42.0.2
  - cudatoolkit=11.6.0
  - cycler=0.12.1
  - cython=0.29.32
  - cytoolz=0.12.3
  - dask-core=2023.10.1
  - dataclasses=0.8
  - datasets=2.6.1
  - dav1d=1.0.0
  - dbus=1.13.6
  - debugpy=1.8.5
  - decorator=5.1.1
  - diffusers=0.11.1
  - dill=0.3.5.1
  - docker-pycreds=0.4.0
  - einops=0.4.1
  - elfutils=0.189
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.3
  - ffmpeg=4.4.2
  - fftw=3.3.10
  - filelock=3.16.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.54.0
  - freeglut=3.2.2
  - freetype=2.12.1
  - frozenlist=1.4.1
  - fsspec=2024.9.0
  - fvcore=0.1.5.post20221221
  - geos=3.11.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glib=2.80.2
  - glib-tools=2.80.2
  - glog=0.7.1
  - gmp=6.3.0
  - gnutls=3.7.9
  - google-auth=2.35.0
  - google-auth-oauthlib=0.4.6
  - graphite2=1.3.13
  - grpc-cpp=1.46.3
  - grpcio=1.46.3
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - gstreamer-orc=0.4.40
  - gym=0.21.0
  - h5py=3.7.0
  - harfbuzz=5.3.0
  - hdf5=1.12.2
  - huggingface_hub=0.25.1
  - hydra-core=1.2.0
  - icu=70.1
  - idna=3.10
  - imageio=2.22.0
  - imageio-ffmpeg=0.4.7
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.5
  - intel-openmp=2022.1.0
  - iopath=0.1.10
  - ipykernel=6.16.2
  - ipython=8.18.1
  - jack=1.9.22
  - jasper=2.0.33
  - jedi=0.19.1
  - jmespath=1.0.1
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.14
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20211102.0
  - libaec=1.1.3
  - libarchive=3.6.2
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libavif=0.10.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libcurl=8.1.2
  - libdb=6.2.32
  - libdeflate=1.14
  - libdrm=2.4.123
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.6.3
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgcrypt=1.11.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.2
  - libglu=9.0.0
  - libgomp=14.1.0
  - libgpg-error=1.50
  - libiconv=1.17
  - libidn2=2.3.7
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libllvm15=15.0.7
  - libllvm16=16.0.1
  - libmicrohttpd=0.9.77
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopencv=4.6.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.43
  - libpq=15.3
  - libprotobuf=3.20.1
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libsystemd0=253
  - libtasn1=4.19.0
  - libthrift=0.15.0
  - libtiff=4.4.0
  - libtool=2.4.7
  - libudev1=253
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libuv=1.48.0
  - libva=2.18.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.4.0
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=14.0.6
  - locket=1.0.0
  - lz4-c=1.9.4
  - lzo=2.10
  - markdown=3.6
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.7
  - mesalib=23.0.2
  - mkl=2022.1.0
  - mpg123=1.32.6
  - msgpack-python=1.1.0
  - multidict=6.1.0
  - multiprocess=0.70.14
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.2.1
  - nspr=4.35
  - nss=3.100
  - numcodecs=0.10.2
  - numpy=1.23.3
  - oauthlib=3.2.2
  - omegaconf=2.2.3
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.1.7
  - orc=1.7.4
  - p11-kit=0.24.1
  - packaging=24.1
  - pandas=2.2.3
  - parso=0.8.4
  - partd=1.4.2
  - pathtools=0.1.2
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - pixman=0.43.2
  - platformdirs=4.3.6
  - ply=3.11
  - portalocker=2.10.1
  - promise=2.3
  - prompt-toolkit=3.0.47
  - psutil=5.9.2
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pure_eval=0.2.3
  - py-opencv=4.6.0
  - pyarrow=8.0.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pygments=2.18.0
  - pyjwt=2.9.0
  - pymunk=6.2.1
  - pyopenssl=24.2.1
  - pyparsing=3.1.4
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - python-xxhash=3.5.0
  - python_abi=3.9
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - pytorch3d=0.7.0
  - pytz=2024.1
  - pyu2f=0.1.5
  - pywavelets=1.6.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt-main=5.15.6
  - re2=2022.04.01
  - readline=8.2
  - regex=2024.9.11
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - responses=0.18.0
  - rhash=1.4.3
  - rsa=4.9
  - s3transfer=0.6.2
  - scikit-image=0.19.3
  - scikit-video=1.1.11
  - scipy=1.9.1
  - sentry-sdk=2.14.0
  - setproctitle=1.3.3
  - setuptools=74.1.2
  - shapely=1.8.4
  - shortuuid=1.0.13
  - sip=6.7.12
  - six=1.16.0
  - smmap=5.0.0
  - snappy=1.1.10
  - stack_data=0.6.2
  - svt-av1=1.4.1
  - tabulate=0.9.0
  - tensorboard=2.10.1
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorboardx=2.5.1
  - termcolor=2.0.1
  - threadpoolctl=3.1.0
  - tifffile=2022.10.10
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.1
  - torchvision=0.13.1
  - tornado=6.4.1
  - tqdm=4.64.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=1.26.19
  - utf8proc=2.6.1
  - wandb=0.13.3
  - wcwidth=0.2.13
  - werkzeug=3.0.4
  - wheel=0.44.0
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-damageproto=1.2.1
  - xorg-fixesproto=5.0
  - xorg-glproto=1.4.17
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdamage=1.1.5
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrandr=1.5.2
  - xorg-libxrender=0.9.10
  - xorg-randrproto=1.5.0
  - xorg-renderproto=0.11.1
  - xorg-util-macros=1.20.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xxhash=0.8.2
  - xz=5.2.6
  - yacs=0.1.8
  - yaml=0.2.5
  - yarl=1.9.4
  - zarr=2.12.0
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.20.2
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.6
  - pip:
      - aiohttp-cors==0.7.0
      - annotated-types==0.7.0
      - beautifulsoup4==4.12.3
      - blessed==1.20.0
      - chardet==5.2.0
      - colorful==0.5.6
      - distlib==0.3.8
      - dm-control==1.0.9
      - dm-env==1.6
      - dm-tree==0.1.8
      - egl-probe==1.0.2
      - etils==1.5.2
      - evdev==1.7.1
      - fasteners==0.15
      - free-mujoco-py==2.1.6
      - gdown==5.2.0
      - glfw==1.12.0
      - google-api-core==2.20.0
      - googleapis-common-protos==1.63.1
      - gpustat==1.1.1
      - imagecodecs==2022.9.26
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - labmaze==1.0.6
      - llvmlite==0.36.0
      - lxml==5.3.0
      - matplotlib==3.9.2
      - monotonic==1.6
      - mujoco==3.2.3
      - mujoco-py==2.1.2.14
      - numba==0.53.1
      - nvidia-ml-py==12.560.30
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - parameterized==0.9.0
      - prometheus-client==0.13.1
      - proto-plus==1.24.0
      - protobuf==3.19.6
      - py-spy==0.3.14
      - pybullet-svl==3.1.6.4
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pygame==2.1.2
      - pynput==1.7.7
      - pyopengl==3.1.7
      - python-xlib==0.33
      - pytorchvideo==0.1.5
      - r3m==0.0.0
      - ray==2.2.0
      - referencing==0.35.1
      - robomimic==0.2.0
      - robosuite==1.4.1
      - rpds-py==0.20.0
      - seaborn==0.13.2
      - smart-open==7.0.4
      - soupsieve==2.6
      - virtualenv==20.26.5
      - wrapt==1.16.0
